### ISSUE TITLE
Exception while linting files

### ISSUE THREAD

**Issue by axelson** [pmndrs/eslint-plugin-valtio#24]
Here's a slightly sanitized stacktrace:
```
$ eslint . --ext .js,.jsx,.ts,.tsx --color

Oops! Something went wrong! :(

ESLint: 8.15.0

TypeError: Cannot read properties of undefined (reading 'type')
Occurred while linting /Users/jason/my_app/js/hooks/useDragElement.ts:45
Rule: "valtio/state-snapshot-rule"
    at /Users/jason/my_app/node_modules/eslint-plugin-valtio/index.js:383:36
    at Array.forEach (<anonymous>)
    at isUsedInUseProxy (/Users/jason/my_app/node_modules/eslint-plugin-valtio/index.js:374:19)
    at isUsedInUseProxy (/Users/jason/my_app/node_modules/eslint-plugin-valtio/index.js:388:47)
    at Identifier (/Users/jason/my_app/node_modules/eslint-plugin-valtio/index.js:200:225)
    at ruleErrorHandler (/Users/jason/my_app/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /Users/jason/my_app/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/jason/my_app/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/jason/my_app/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
```

I'm not quite sure how to create a code sandbox that reproduces the error because I don't see a way to run eslint in the code sandbox, but here's a codesandbox that has the bits of the file that seem most relevant:
https://codesandbox.io/s/nifty-sound-thwx6r?file=/src/lib/useDrag.ts

**Comment by dai-shi** [comment]
@barelyhuman Can you take a look?

**Comment by barelyhuman** [comment]
i’ll check into it
